name: ns_utils
description: Set of methods/extentions for flutter that makes using framework in a much easier and clean way also adds additional functionality.
version: 1.1.0
documentation: https://github.com/ajaykumargithub2114/ns_utils
homepage: https://github.com/ajaykumargithub2114/ns_utils

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  #<editor-fold desc="UI">
  flutter_spinkit: ^5.1.0
  #</editor-fold>

  #<editor-fold desc="UTILS">
  intl: ^0.17.0
  flutter_screenutil: 5.1.0
  recase: ^4.0.0
  after_layout: ^1.1.0
  cached_network_image: ^3.2.0
  focus_detector: ^2.0.1
  visibility_detector: ^0.2.2
  #</editor-fold>

  #<editor-fold desc="LOCAL-DATABASE">
  shared_preferences: ^2.0.12
  #</editor-fold>

  #<editor-fold desc="DEVICE APIS">
  device_info_plus: ^3.2.1
  package_info_plus: ^1.3.0
  #</editor-fold>

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.2

flutter:

